### ISSUE TITLE
**********Enumerate Discover Mode********** 发生错误

### ISSUE THREAD

**Issue by ldbfpiaoran** [coco413/DiscoverSubdomain#1]
**********Enumerate Discover Mode**********
Traceback (most recent call last):
  File "DiscoverSubdomain.py", line 84, in main
    domains = SubNameBrute(target=self.domain, threads=self.thread, mode=self.mode).run()
  File "/root/DiscoverSubdomain/brute/subDomainsBrute.py", line 35, in __init__
    self.threads)]
TypeError: range() integer end argument expected, got str.

还有就是requirements.txt  里platform 貌似是python自带库 
安装时候报错~~

**Comment by coco413** [comment]
谢谢,已经修改，第一个从命令行传线程数类型没做好转换。第二个platform模块已从requirements.txt移除
