### ISSUE TITLE
线程貌似有问题 

### ISSUE THREAD

**Issue by ldbfpiaoran** [coco413/DiscoverSubdomain#2]
不知道应该和机器有关么 
1h1g vps 装的kaili最新的
开100线程的时候 需要做一个ctrl+c操作跳出第一个
然后我开了30线程
扫描banner会报错
Traceback (most recent call last):
  File "/root/DiscoverSubdomain/lib/simple_assets.py", line 27, in GetBanner
    r = requests.get(url, timeout=10, verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 634, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 134, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
TooManyRedirects: Exceeded 30 redirects.

不知道是是不是链接超时导致的

**Comment by coco413** [comment]
你pull下最新代码，这个之前我也遇到过已经修改了，重定向关掉就可以了 allow_redirects=False

**Comment by ldbfpiaoran** [comment]
好的
